export enum CardStatusEnum {
  PRE_ORDER = 'PRE_ORDER',
  NOT_ORDERED = 'NOT_ORDERED',
  STARTED = 'STARTED',
  INACTIVE = 'INACTIVE',
  PROCESSING = 'PROCESSING',
  ACTIVE = 'ACTIVE',
  COUNTERFEIT_CARD = 'COUNTERFEIT_CARD',
  FRAUD = 'FRAUD',
  LOST = 'LOST',
  STOLEN = 'STOLEN',
  NEVER_RECEIVED = 'NEVER_RECEIVED',
  BLOCKED = 'BLOCKED',
}

export enum CardTypeEnum {
  VIRTUAL = 'VIRTUAL_MASTERCARD_DEBIT',
  STANDARD = 'MASTERCARD_DEBIT',
}

export enum CardLostReasonEnum {
  HOME_INVASION = 'HOME_INVASION',
  PICK_POCKET = 'PICK_POCKET',
  LEFT_AT_MERCHANT = 'LEFT_AT_MERCHANT',
  LOST = 'LOST',
  MISSING_AT_HOME = 'MISSING_AT_HOME',
  SUSPECTED_MERCHANT_FRAUD = 'SUSPECTED_MERCHANT_FRAUD',
  MAIL_ORDER = 'MAIL_ORDER',
  MAILBOX_THEFT = 'MAILBOX_THEFT',
  COUNTERFEIT_PLASTIC = 'COUNTERFEIT_PLASTIC',
  PREVENTIVE_BLOCK = 'PREVENTIVE_BLOCK',
}
