import * as dotenv from 'dotenv';

dotenv.config();

const SKIP_JOB_RUN_TOTAL_BALANCE = process.env.SKIP_JOB_RUN_TOTAL_BALANCE;
const INTERCOM_USER_BLOCKED_TAG_ID = '6650624';
const INTERCOM_PRIME_TRUST_EXCHANGE = '6693377';

export {
  SKIP_JOB_RUN_TOTAL_BALANCE,
  INTERCOM_USER_BLOCKED_TAG_ID,
  INTERCOM_PRIME_TRUST_EXCHANGE,
};
