import * as dotenv from 'dotenv';

dotenv.config();

const USE_SWAGGER = process.env.USE_SWAGGER;
const LOGS_SOURCE_FILE = process.env.LOGS_SOURCE_FILE;

const WYRE_ACCOUNT_ID = '';
const WYRE_SECRET_KEY = '';
const WYRE_API_ENDPOINT = '';

const PLAID_CLIENT_ID = process.env.PLAID_CLIENT_ID;
const PLAID_SECRET = process.env.PLAID_SECRET;
const PLAID_ENV = process.env.PLAID_ENV;
const INTERCOM_API = 'https://api.intercom.io';
const INTERCOM_ACCESS_TOKEN = process.env.INTERCOM_ACCESS_TOKEN;
const INTERCOM_TAG_ONBOARDING_COMPLETE = 'OnboardingComplete';
const INTERCOM_TAG_ACCOUNT_FEATURE_INFO = 'AccountFeaturesInfo';
const INTERCOM_TAG_TOKEN_ANIMATION = 'Dev_TokenAnimation';
const TWILIO_SERVICE_TOKEN = process.env.TWILIO_SERVICE_TOKEN;
const TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN;
const TWILIO_ACCOUNT_SID = process.env.TWILIO_ACCOUNT_SID;
const BAANX_API = 'https://intellabridge.baanx.co.uk/iframe/api';
const BAANX_ACCESS_TOKEN = process.env.BAANX_ACCESS_TOKEN;
const NEWS_API = process.env.NEWS_API;
const MORALIS_API_KEY =
  'j6ymL4wHcbRlGbIzVMwPXR7aBMF8iZeWA2oolIZijpGA29KQm4phD5d2FKbox5eI';

const MONGODB_URL = process.env.DATABASE_URI;
const GENERAL_KEY = process.env.MASTER_KEY;
/// Prime Trust Username : csa3@gmail.com Password: Coded@123.
const PRIME_TRUST_API = process.env.PRIME_TRUST_API;
const PRIME_TRUST_TOKEN = process.env.PRIME_TRUST_TOKEN;
const PRIME_TRUST_HOOK = process.env.PRIME_TRUST_HOOK;
const PRIME_TRUST_MAIL = process.env.PRIME_TRUST_MAIL;

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
const TX_LOGS_MASTER_KEY = process.env.MASTER_KEY;
const USER_BALANCES_MASTER_KEY = process.env.MASTER_KEY;
const USER_CONTACTS_MASTER_KEY = process.env.MASTER_KEY;
const BAANX_MASTER_KEY = process.env.BAANX_MASTER_KEY;
const PRIME_TRUST_MASTER_KEY = process.env.PRIME_TRUST_MASTER_KEY;
const PRIME_TRUST_UST_ADDRESS = process.env.PT_UST_ADDRESS;

export {
  BAANX_API,
  TX_LOGS_MASTER_KEY,
  BAANX_MASTER_KEY,
  MONGODB_URL,
  INTERCOM_API,
  BAANX_ACCESS_TOKEN,
  INTERCOM_ACCESS_TOKEN,
  INTERCOM_TAG_ONBOARDING_COMPLETE,
  TWILIO_SERVICE_TOKEN,
  TWILIO_AUTH_TOKEN,
  TWILIO_ACCOUNT_SID,
  INTERCOM_TAG_TOKEN_ANIMATION,
  NEWS_API,
  MORALIS_API_KEY,
  USER_BALANCES_MASTER_KEY,
  PRIME_TRUST_API,
  PRIME_TRUST_TOKEN,
  PRIME_TRUST_MASTER_KEY,
  WYRE_ACCOUNT_ID,
  WYRE_SECRET_KEY,
  WYRE_API_ENDPOINT,
  PLAID_CLIENT_ID,
  PLAID_SECRET,
  PLAID_ENV,
  USER_CONTACTS_MASTER_KEY,
  GENERAL_KEY,
  PRIME_TRUST_HOOK,
  SENDGRID_API_KEY,
  USE_SWAGGER,
  PRIME_TRUST_MAIL,
  INTERCOM_TAG_ACCOUNT_FEATURE_INFO,
  LOGS_SOURCE_FILE,
  PRIME_TRUST_UST_ADDRESS,
};
